name: Lint Filenames

on:
  push:
    branches:
      - '**'  # All branches
    paths:
      - "**"  # All paths

jobs:
  filename-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check filenames
        run: bash scripts/lint/check-filenames.sh .