name: Validate SVG Icons

on:
  push:
    branches:
      - '**'  # All branches
    paths:
      - "assets/icons/**.svg" # Only SVGs

jobs:
  svg-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check SVG icons
        run: bash scripts/lint/check-svg.sh